version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-2.7
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip gtkwave libgnat-4.8 pandoc
            wget https://github.com/tgingold/ghdl/releases/download/v0.33/ghdl_0.33-1ubuntu1_amd64.deb
            sudo dpkg --install ghdl_0.33-1ubuntu1_amd64.deb
            pip install rst2pdf

      - run: make gen
      - run: make compile_ghdl

  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-jessie
