version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-2.7
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6-buster
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y pandoc
            sudo apt-get install ghdl gtkwave
            sudo pip install rst2pdf
            sudo pip install --upgrade -r requirements.txt

      - run: make gen
      - run: make compile_ghdl

  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-buster
