version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.11

jobs:
  test-3.11: &test-template
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y pandoc ghdl gtkwave verilator python3-pip
            pip install -e .

      - run: python --version
      - run: make gen
      - run: make compile_ghdl
      - run: make compile_verilator
      - run: make test_c

